// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: strix_mesh.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EPBMsgType int32

const (
	EPBMsgType_PBMT_NONE                       EPBMsgType = 0
	EPBMsgType_PBMT_MIN                        EPBMsgType = 100
	EPBMsgType_PBMT_NTY_UNIXSOCK_HEATBEAT      EPBMsgType = 201
	EPBMsgType_PBMT_REQ_UNIXSOCK_REGISTER      EPBMsgType = 203
	EPBMsgType_PBMT_RSP_UNIXSOCK_REGISTER      EPBMsgType = 204
	EPBMsgType_PBMT_NTY_UNIXSOCK_CONNECT       EPBMsgType = 205
	EPBMsgType_PBMT_NTY_UNIXSOCK_DISCONNECT    EPBMsgType = 207
	EPBMsgType_PBMT_NTY_UNIXSOCK_RECVEVENTFD   EPBMsgType = 209
	EPBMsgType_PBMT_NTY_UNIXSOCK_UNREGISTER    EPBMsgType = 211
	EPBMsgType_PBMT_NTY_UNIXSOCK_DYNAMIC_LOAD  EPBMsgType = 213
	EPBMsgType_PBMT_REQ_UNIXSOCK_CHG_PIPEIDX   EPBMsgType = 214
	EPBMsgType_PBMT_RES_UNIXSOCK_CHG_PIPEIDX   EPBMsgType = 215
	EPBMsgType_PBMT_NTY_NET_HEATBEAT           EPBMsgType = 301
	EPBMsgType_PBMT_REQ_NET_REGISTER           EPBMsgType = 302
	EPBMsgType_PBMT_RSP_NET_REGISTER           EPBMsgType = 303
	EPBMsgType_PBMT_REQ_ROUTER_REGISTER        EPBMsgType = 601
	EPBMsgType_PBMT_RES_ROUTER_REGISTER        EPBMsgType = 602
	EPBMsgType_PBMT_REQ_ROUTER_UNREGISTER      EPBMsgType = 603
	EPBMsgType_PBMT_RES_ROUTER_UNREGISTER      EPBMsgType = 604
	EPBMsgType_PBMT_REQ_START_MIGRATE          EPBMsgType = 801
	EPBMsgType_PBMT_RES_START_MIGRATE          EPBMsgType = 802
	EPBMsgType_PBMT_NTY_SIDECAR_MIGRATE_FINISH EPBMsgType = 803
	EPBMsgType_PBMT_NTY_BACKENDSVR_STOP        EPBMsgType = 804
	EPBMsgType_PBMT_NTY_NEWSVR_MIGRATE_FINISH  EPBMsgType = 805
	EPBMsgType_PBMT_MAX                        EPBMsgType = 60000
)

// Enum value maps for EPBMsgType.
var (
	EPBMsgType_name = map[int32]string{
		0:     "PBMT_NONE",
		100:   "PBMT_MIN",
		201:   "PBMT_NTY_UNIXSOCK_HEATBEAT",
		203:   "PBMT_REQ_UNIXSOCK_REGISTER",
		204:   "PBMT_RSP_UNIXSOCK_REGISTER",
		205:   "PBMT_NTY_UNIXSOCK_CONNECT",
		207:   "PBMT_NTY_UNIXSOCK_DISCONNECT",
		209:   "PBMT_NTY_UNIXSOCK_RECVEVENTFD",
		211:   "PBMT_NTY_UNIXSOCK_UNREGISTER",
		213:   "PBMT_NTY_UNIXSOCK_DYNAMIC_LOAD",
		214:   "PBMT_REQ_UNIXSOCK_CHG_PIPEIDX",
		215:   "PBMT_RES_UNIXSOCK_CHG_PIPEIDX",
		301:   "PBMT_NTY_NET_HEATBEAT",
		302:   "PBMT_REQ_NET_REGISTER",
		303:   "PBMT_RSP_NET_REGISTER",
		601:   "PBMT_REQ_ROUTER_REGISTER",
		602:   "PBMT_RES_ROUTER_REGISTER",
		603:   "PBMT_REQ_ROUTER_UNREGISTER",
		604:   "PBMT_RES_ROUTER_UNREGISTER",
		801:   "PBMT_REQ_START_MIGRATE",
		802:   "PBMT_RES_START_MIGRATE",
		803:   "PBMT_NTY_SIDECAR_MIGRATE_FINISH",
		804:   "PBMT_NTY_BACKENDSVR_STOP",
		805:   "PBMT_NTY_NEWSVR_MIGRATE_FINISH",
		60000: "PBMT_MAX",
	}
	EPBMsgType_value = map[string]int32{
		"PBMT_NONE":                       0,
		"PBMT_MIN":                        100,
		"PBMT_NTY_UNIXSOCK_HEATBEAT":      201,
		"PBMT_REQ_UNIXSOCK_REGISTER":      203,
		"PBMT_RSP_UNIXSOCK_REGISTER":      204,
		"PBMT_NTY_UNIXSOCK_CONNECT":       205,
		"PBMT_NTY_UNIXSOCK_DISCONNECT":    207,
		"PBMT_NTY_UNIXSOCK_RECVEVENTFD":   209,
		"PBMT_NTY_UNIXSOCK_UNREGISTER":    211,
		"PBMT_NTY_UNIXSOCK_DYNAMIC_LOAD":  213,
		"PBMT_REQ_UNIXSOCK_CHG_PIPEIDX":   214,
		"PBMT_RES_UNIXSOCK_CHG_PIPEIDX":   215,
		"PBMT_NTY_NET_HEATBEAT":           301,
		"PBMT_REQ_NET_REGISTER":           302,
		"PBMT_RSP_NET_REGISTER":           303,
		"PBMT_REQ_ROUTER_REGISTER":        601,
		"PBMT_RES_ROUTER_REGISTER":        602,
		"PBMT_REQ_ROUTER_UNREGISTER":      603,
		"PBMT_RES_ROUTER_UNREGISTER":      604,
		"PBMT_REQ_START_MIGRATE":          801,
		"PBMT_RES_START_MIGRATE":          802,
		"PBMT_NTY_SIDECAR_MIGRATE_FINISH": 803,
		"PBMT_NTY_BACKENDSVR_STOP":        804,
		"PBMT_NTY_NEWSVR_MIGRATE_FINISH":  805,
		"PBMT_MAX":                        60000,
	}
)

func (x EPBMsgType) Enum() *EPBMsgType {
	p := new(EPBMsgType)
	*p = x
	return p
}

func (x EPBMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EPBMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_strix_mesh_proto_enumTypes[0].Descriptor()
}

func (EPBMsgType) Type() protoreflect.EnumType {
	return &file_strix_mesh_proto_enumTypes[0]
}

func (x EPBMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EPBMsgType.Descriptor instead.
func (EPBMsgType) EnumDescriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{0}
}

// Server status
type ESvrState int32

const (
	ESvrState_ST_HEALTH        ESvrState = 0 // Healthy (will set itself to a healthy state in consul)
	ESvrState_ST_GRACEFUL_EXIT ESvrState = 1 // In graceful exit (will set itself to a grayscale state in consul, this state is used during grayscale updates)
	ESvrState_ST_FASTEXIT      ESvrState = 2 // Shared memory restart (will set itself to a healthy state in consul)
)

// Enum value maps for ESvrState.
var (
	ESvrState_name = map[int32]string{
		0: "ST_HEALTH",
		1: "ST_GRACEFUL_EXIT",
		2: "ST_FASTEXIT",
	}
	ESvrState_value = map[string]int32{
		"ST_HEALTH":        0,
		"ST_GRACEFUL_EXIT": 1,
		"ST_FASTEXIT":      2,
	}
)

func (x ESvrState) Enum() *ESvrState {
	p := new(ESvrState)
	*p = x
	return p
}

func (x ESvrState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESvrState) Descriptor() protoreflect.EnumDescriptor {
	return file_strix_mesh_proto_enumTypes[1].Descriptor()
}

func (ESvrState) Type() protoreflect.EnumType {
	return &file_strix_mesh_proto_enumTypes[1]
}

func (x ESvrState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ESvrState.Descriptor instead.
func (ESvrState) EnumDescriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{1}
}

type NamingRegiserOption struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IsStatefulService   bool                   `protobuf:"varint,1,opt,name=is_stateful_service,json=isStatefulService,proto3" json:"is_stateful_service,omitempty"`       // Whether it is a stateful service
	NeedMasterSelection bool                   `protobuf:"varint,2,opt,name=need_master_selection,json=needMasterSelection,proto3" json:"need_master_selection,omitempty"` // Whether to participate in master selection
	NeedBackup          bool                   `protobuf:"varint,3,opt,name=need_backup,json=needBackup,proto3" json:"need_backup,omitempty"`                              // Whether a backup is needed
	StaticWeight        int32                  `protobuf:"varint,4,opt,name=static_weight,json=staticWeight,proto3" json:"static_weight,omitempty"`                        // Static weight
	DynamicWeight       int32                  `protobuf:"varint,5,opt,name=dynamic_weight,json=dynamicWeight,proto3" json:"dynamic_weight,omitempty"`                     // Dynamic weight
	IsHealth            bool                   `protobuf:"varint,6,opt,name=is_health,json=isHealth,proto3" json:"is_health,omitempty"`                                    // Whether it is in a healthy state at the time of registration
	PipeIdx             int32                  `protobuf:"varint,7,opt,name=pipe_idx,json=pipeIdx,proto3" json:"pipe_idx,omitempty"`                                       // shm pipe index
	SvrUnqueid          uint32                 `protobuf:"varint,8,opt,name=svr_unqueid,json=svrUnqueid,proto3" json:"svr_unqueid,omitempty"`                              // Unique process identifier, used to distinguish between old and new processes with the same process ID
	Version             int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`                                                      // Identifier sent by the sidecar to the process
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NamingRegiserOption) Reset() {
	*x = NamingRegiserOption{}
	mi := &file_strix_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamingRegiserOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamingRegiserOption) ProtoMessage() {}

func (x *NamingRegiserOption) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamingRegiserOption.ProtoReflect.Descriptor instead.
func (*NamingRegiserOption) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *NamingRegiserOption) GetIsStatefulService() bool {
	if x != nil {
		return x.IsStatefulService
	}
	return false
}

func (x *NamingRegiserOption) GetNeedMasterSelection() bool {
	if x != nil {
		return x.NeedMasterSelection
	}
	return false
}

func (x *NamingRegiserOption) GetNeedBackup() bool {
	if x != nil {
		return x.NeedBackup
	}
	return false
}

func (x *NamingRegiserOption) GetStaticWeight() int32 {
	if x != nil {
		return x.StaticWeight
	}
	return 0
}

func (x *NamingRegiserOption) GetDynamicWeight() int32 {
	if x != nil {
		return x.DynamicWeight
	}
	return 0
}

func (x *NamingRegiserOption) GetIsHealth() bool {
	if x != nil {
		return x.IsHealth
	}
	return false
}

func (x *NamingRegiserOption) GetPipeIdx() int32 {
	if x != nil {
		return x.PipeIdx
	}
	return 0
}

func (x *NamingRegiserOption) GetSvrUnqueid() uint32 {
	if x != nil {
		return x.SvrUnqueid
	}
	return 0
}

func (x *NamingRegiserOption) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ServiceQueryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	ServiceID     string                 `protobuf:"bytes,2,opt,name=ServiceID,proto3" json:"ServiceID,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=Tags,proto3" json:"Tags,omitempty"`
	SetVersion    uint64                 `protobuf:"varint,4,opt,name=SetVersion,proto3" json:"SetVersion,omitempty"` // The Set version number of the server, e.g., 2024030812350943
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceQueryInfo) Reset() {
	*x = ServiceQueryInfo{}
	mi := &file_strix_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceQueryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceQueryInfo) ProtoMessage() {}

func (x *ServiceQueryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceQueryInfo.ProtoReflect.Descriptor instead.
func (*ServiceQueryInfo) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceQueryInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceQueryInfo) GetServiceID() string {
	if x != nil {
		return x.ServiceID
	}
	return ""
}

func (x *ServiceQueryInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ServiceQueryInfo) GetSetVersion() uint64 {
	if x != nil {
		return x.SetVersion
	}
	return 0
}

type MsgRspResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRspResult) Reset() {
	*x = MsgRspResult{}
	mi := &file_strix_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRspResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRspResult) ProtoMessage() {}

func (x *MsgRspResult) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRspResult.ProtoReflect.Descriptor instead.
func (*MsgRspResult) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *MsgRspResult) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *MsgRspResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MsgNtyUnixSockHeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         ESvrState              `protobuf:"varint,1,opt,name=state,proto3,enum=mesh.ESvrState" json:"state,omitempty"`
	PipeIdx       int32                  `protobuf:"varint,2,opt,name=pipe_idx,json=pipeIdx,proto3" json:"pipe_idx,omitempty"`          // shm pipe index
	SvrUnqueid    uint32                 `protobuf:"varint,3,opt,name=svr_unqueid,json=svrUnqueid,proto3" json:"svr_unqueid,omitempty"` // Unique process identifier, used to distinguish between old and new processes with the same process ID
	SetVersion    uint64                 `protobuf:"varint,4,opt,name=set_version,json=setVersion,proto3" json:"set_version,omitempty"` // The Set version number of the server, e.g., 2024030812350943
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgNtyUnixSockHeartBeat) Reset() {
	*x = MsgNtyUnixSockHeartBeat{}
	mi := &file_strix_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgNtyUnixSockHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgNtyUnixSockHeartBeat) ProtoMessage() {}

func (x *MsgNtyUnixSockHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgNtyUnixSockHeartBeat.ProtoReflect.Descriptor instead.
func (*MsgNtyUnixSockHeartBeat) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *MsgNtyUnixSockHeartBeat) GetState() ESvrState {
	if x != nil {
		return x.State
	}
	return ESvrState_ST_HEALTH
}

func (x *MsgNtyUnixSockHeartBeat) GetPipeIdx() int32 {
	if x != nil {
		return x.PipeIdx
	}
	return 0
}

func (x *MsgNtyUnixSockHeartBeat) GetSvrUnqueid() uint32 {
	if x != nil {
		return x.SvrUnqueid
	}
	return 0
}

func (x *MsgNtyUnixSockHeartBeat) GetSetVersion() uint64 {
	if x != nil {
		return x.SetVersion
	}
	return 0
}

type MsgReqUnixSockRegister struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SvcInfo        *ServiceQueryInfo      `protobuf:"bytes,1,opt,name=svc_info,json=svcInfo,proto3" json:"svc_info,omitempty"`
	RegisterOption *NamingRegiserOption   `protobuf:"bytes,2,opt,name=register_option,json=registerOption,proto3" json:"register_option,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgReqUnixSockRegister) Reset() {
	*x = MsgReqUnixSockRegister{}
	mi := &file_strix_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgReqUnixSockRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReqUnixSockRegister) ProtoMessage() {}

func (x *MsgReqUnixSockRegister) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReqUnixSockRegister.ProtoReflect.Descriptor instead.
func (*MsgReqUnixSockRegister) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *MsgReqUnixSockRegister) GetSvcInfo() *ServiceQueryInfo {
	if x != nil {
		return x.SvcInfo
	}
	return nil
}

func (x *MsgReqUnixSockRegister) GetRegisterOption() *NamingRegiserOption {
	if x != nil {
		return x.RegisterOption
	}
	return nil
}

type MsgResUnixSockRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *MsgRspResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	IsMain        int32                  `protobuf:"varint,2,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	NeedMigreate  int32                  `protobuf:"varint,3,opt,name=need_migreate,json=needMigreate,proto3" json:"need_migreate,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // Identifier sent by the sidecar to the process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgResUnixSockRegister) Reset() {
	*x = MsgResUnixSockRegister{}
	mi := &file_strix_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgResUnixSockRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResUnixSockRegister) ProtoMessage() {}

func (x *MsgResUnixSockRegister) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResUnixSockRegister.ProtoReflect.Descriptor instead.
func (*MsgResUnixSockRegister) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *MsgResUnixSockRegister) GetResult() *MsgRspResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MsgResUnixSockRegister) GetIsMain() int32 {
	if x != nil {
		return x.IsMain
	}
	return 0
}

func (x *MsgResUnixSockRegister) GetNeedMigreate() int32 {
	if x != nil {
		return x.NeedMigreate
	}
	return 0
}

func (x *MsgResUnixSockRegister) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type MsgReqUnixSockChgPipeIdx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeidx       int32                  `protobuf:"varint,1,opt,name=pipeidx,proto3" json:"pipeidx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgReqUnixSockChgPipeIdx) Reset() {
	*x = MsgReqUnixSockChgPipeIdx{}
	mi := &file_strix_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgReqUnixSockChgPipeIdx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReqUnixSockChgPipeIdx) ProtoMessage() {}

func (x *MsgReqUnixSockChgPipeIdx) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReqUnixSockChgPipeIdx.ProtoReflect.Descriptor instead.
func (*MsgReqUnixSockChgPipeIdx) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *MsgReqUnixSockChgPipeIdx) GetPipeidx() int32 {
	if x != nil {
		return x.Pipeidx
	}
	return 0
}

type MsgResUnixSockChgPipeIdx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgResUnixSockChgPipeIdx) Reset() {
	*x = MsgResUnixSockChgPipeIdx{}
	mi := &file_strix_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgResUnixSockChgPipeIdx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResUnixSockChgPipeIdx) ProtoMessage() {}

func (x *MsgResUnixSockChgPipeIdx) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResUnixSockChgPipeIdx.ProtoReflect.Descriptor instead.
func (*MsgResUnixSockChgPipeIdx) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *MsgResUnixSockChgPipeIdx) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MsgNtyUnixSockUnRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         int32                  `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	PipeIdx       int32                  `protobuf:"varint,3,opt,name=pipe_idx,json=pipeIdx,proto3" json:"pipe_idx,omitempty"`          // shm pipe index
	SvrUnqueid    uint32                 `protobuf:"varint,4,opt,name=svr_unqueid,json=svrUnqueid,proto3" json:"svr_unqueid,omitempty"` // Unique process identifier, used to distinguish between old and new processes with the same process ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgNtyUnixSockUnRegister) Reset() {
	*x = MsgNtyUnixSockUnRegister{}
	mi := &file_strix_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgNtyUnixSockUnRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgNtyUnixSockUnRegister) ProtoMessage() {}

func (x *MsgNtyUnixSockUnRegister) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgNtyUnixSockUnRegister.ProtoReflect.Descriptor instead.
func (*MsgNtyUnixSockUnRegister) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *MsgNtyUnixSockUnRegister) GetDummy() int32 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

func (x *MsgNtyUnixSockUnRegister) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *MsgNtyUnixSockUnRegister) GetPipeIdx() int32 {
	if x != nil {
		return x.PipeIdx
	}
	return 0
}

func (x *MsgNtyUnixSockUnRegister) GetSvrUnqueid() uint32 {
	if x != nil {
		return x.SvrUnqueid
	}
	return 0
}

type MsgNtyUnixSockDynamicLoad struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceId           string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	DynamicLoad         int64                  `protobuf:"varint,2,opt,name=dynamic_load,json=dynamicLoad,proto3" json:"dynamic_load,omitempty"`
	DynamicLoadCapacity int64                  `protobuf:"varint,3,opt,name=dynamic_load_capacity,json=dynamicLoadCapacity,proto3" json:"dynamic_load_capacity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MsgNtyUnixSockDynamicLoad) Reset() {
	*x = MsgNtyUnixSockDynamicLoad{}
	mi := &file_strix_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgNtyUnixSockDynamicLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgNtyUnixSockDynamicLoad) ProtoMessage() {}

func (x *MsgNtyUnixSockDynamicLoad) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgNtyUnixSockDynamicLoad.ProtoReflect.Descriptor instead.
func (*MsgNtyUnixSockDynamicLoad) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *MsgNtyUnixSockDynamicLoad) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *MsgNtyUnixSockDynamicLoad) GetDynamicLoad() int64 {
	if x != nil {
		return x.DynamicLoad
	}
	return 0
}

func (x *MsgNtyUnixSockDynamicLoad) GetDynamicLoadCapacity() int64 {
	if x != nil {
		return x.DynamicLoadCapacity
	}
	return 0
}

type MsgNtyNetHeatBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         int32                  `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgNtyNetHeatBeat) Reset() {
	*x = MsgNtyNetHeatBeat{}
	mi := &file_strix_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgNtyNetHeatBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgNtyNetHeatBeat) ProtoMessage() {}

func (x *MsgNtyNetHeatBeat) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgNtyNetHeatBeat.ProtoReflect.Descriptor instead.
func (*MsgNtyNetHeatBeat) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *MsgNtyNetHeatBeat) GetDummy() int32 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

type MsgReqNetRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcSvcInfo    *ServiceQueryInfo      `protobuf:"bytes,1,opt,name=src_svc_info,json=srcSvcInfo,proto3" json:"src_svc_info,omitempty"`
	DstSvcInfo    *ServiceQueryInfo      `protobuf:"bytes,2,opt,name=dst_svc_info,json=dstSvcInfo,proto3" json:"dst_svc_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgReqNetRegister) Reset() {
	*x = MsgReqNetRegister{}
	mi := &file_strix_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgReqNetRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReqNetRegister) ProtoMessage() {}

func (x *MsgReqNetRegister) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReqNetRegister.ProtoReflect.Descriptor instead.
func (*MsgReqNetRegister) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *MsgReqNetRegister) GetSrcSvcInfo() *ServiceQueryInfo {
	if x != nil {
		return x.SrcSvcInfo
	}
	return nil
}

func (x *MsgReqNetRegister) GetDstSvcInfo() *ServiceQueryInfo {
	if x != nil {
		return x.DstSvcInfo
	}
	return nil
}

type MsgResNetRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *MsgRspResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	SrcSvcInfo    *ServiceQueryInfo      `protobuf:"bytes,2,opt,name=src_svc_info,json=srcSvcInfo,proto3" json:"src_svc_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgResNetRegister) Reset() {
	*x = MsgResNetRegister{}
	mi := &file_strix_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgResNetRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResNetRegister) ProtoMessage() {}

func (x *MsgResNetRegister) ProtoReflect() protoreflect.Message {
	mi := &file_strix_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResNetRegister.ProtoReflect.Descriptor instead.
func (*MsgResNetRegister) Descriptor() ([]byte, []int) {
	return file_strix_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *MsgResNetRegister) GetResult() *MsgRspResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MsgResNetRegister) GetSrcSvcInfo() *ServiceQueryInfo {
	if x != nil {
		return x.SrcSvcInfo
	}
	return nil
}

var File_strix_mesh_proto protoreflect.FileDescriptor

const file_strix_mesh_proto_rawDesc = "" +
	"\n" +
	"\x10strix_mesh.proto\x12\x04mesh\"\xd9\x02\n" +
	"\x13NamingRegiserOption\x12.\n" +
	"\x13is_stateful_service\x18\x01 \x01(\bR\x11isStatefulService\x122\n" +
	"\x15need_master_selection\x18\x02 \x01(\bR\x13needMasterSelection\x12\x1f\n" +
	"\vneed_backup\x18\x03 \x01(\bR\n" +
	"needBackup\x12#\n" +
	"\rstatic_weight\x18\x04 \x01(\x05R\fstaticWeight\x12%\n" +
	"\x0edynamic_weight\x18\x05 \x01(\x05R\rdynamicWeight\x12\x1b\n" +
	"\tis_health\x18\x06 \x01(\bR\bisHealth\x12\x19\n" +
	"\bpipe_idx\x18\a \x01(\x05R\apipeIdx\x12\x1f\n" +
	"\vsvr_unqueid\x18\b \x01(\rR\n" +
	"svrUnqueid\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion\"\x86\x01\n" +
	"\x10ServiceQueryInfo\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x12\x1c\n" +
	"\tServiceID\x18\x02 \x01(\tR\tServiceID\x12\x12\n" +
	"\x04Tags\x18\x03 \x03(\tR\x04Tags\x12\x1e\n" +
	"\n" +
	"SetVersion\x18\x04 \x01(\x04R\n" +
	"SetVersion\"A\n" +
	"\fMsgRspResult\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x9d\x01\n" +
	"\x17MsgNtyUnixSockHeartBeat\x12%\n" +
	"\x05state\x18\x01 \x01(\x0e2\x0f.mesh.ESvrStateR\x05state\x12\x19\n" +
	"\bpipe_idx\x18\x02 \x01(\x05R\apipeIdx\x12\x1f\n" +
	"\vsvr_unqueid\x18\x03 \x01(\rR\n" +
	"svrUnqueid\x12\x1f\n" +
	"\vset_version\x18\x04 \x01(\x04R\n" +
	"setVersion\"\x8f\x01\n" +
	"\x16MsgReqUnixSockRegister\x121\n" +
	"\bsvc_info\x18\x01 \x01(\v2\x16.mesh.ServiceQueryInfoR\asvcInfo\x12B\n" +
	"\x0fregister_option\x18\x02 \x01(\v2\x19.mesh.NamingRegiserOptionR\x0eregisterOption\"\x9c\x01\n" +
	"\x16MsgResUnixSockRegister\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.mesh.MsgRspResultR\x06result\x12\x17\n" +
	"\ais_main\x18\x02 \x01(\x05R\x06isMain\x12#\n" +
	"\rneed_migreate\x18\x03 \x01(\x05R\fneedMigreate\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"4\n" +
	"\x18MsgReqUnixSockChgPipeIdx\x12\x18\n" +
	"\apipeidx\x18\x01 \x01(\x05R\apipeidx\"2\n" +
	"\x18MsgResUnixSockChgPipeIdx\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"\x8b\x01\n" +
	"\x18MsgNtyUnixSockUnRegister\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\x05R\x05dummy\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x19\n" +
	"\bpipe_idx\x18\x03 \x01(\x05R\apipeIdx\x12\x1f\n" +
	"\vsvr_unqueid\x18\x04 \x01(\rR\n" +
	"svrUnqueid\"\x91\x01\n" +
	"\x19MsgNtyUnixSockDynamicLoad\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fdynamic_load\x18\x02 \x01(\x03R\vdynamicLoad\x122\n" +
	"\x15dynamic_load_capacity\x18\x03 \x01(\x03R\x13dynamicLoadCapacity\")\n" +
	"\x11MsgNtyNetHeatBeat\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\x05R\x05dummy\"\x87\x01\n" +
	"\x11MsgReqNetRegister\x128\n" +
	"\fsrc_svc_info\x18\x01 \x01(\v2\x16.mesh.ServiceQueryInfoR\n" +
	"srcSvcInfo\x128\n" +
	"\fdst_svc_info\x18\x02 \x01(\v2\x16.mesh.ServiceQueryInfoR\n" +
	"dstSvcInfo\"y\n" +
	"\x11MsgResNetRegister\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.mesh.MsgRspResultR\x06result\x128\n" +
	"\fsrc_svc_info\x18\x02 \x01(\v2\x16.mesh.ServiceQueryInfoR\n" +
	"srcSvcInfo*\x8b\x06\n" +
	"\n" +
	"EPBMsgType\x12\r\n" +
	"\tPBMT_NONE\x10\x00\x12\f\n" +
	"\bPBMT_MIN\x10d\x12\x1f\n" +
	"\x1aPBMT_NTY_UNIXSOCK_HEATBEAT\x10\xc9\x01\x12\x1f\n" +
	"\x1aPBMT_REQ_UNIXSOCK_REGISTER\x10\xcb\x01\x12\x1f\n" +
	"\x1aPBMT_RSP_UNIXSOCK_REGISTER\x10\xcc\x01\x12\x1e\n" +
	"\x19PBMT_NTY_UNIXSOCK_CONNECT\x10\xcd\x01\x12!\n" +
	"\x1cPBMT_NTY_UNIXSOCK_DISCONNECT\x10\xcf\x01\x12\"\n" +
	"\x1dPBMT_NTY_UNIXSOCK_RECVEVENTFD\x10\xd1\x01\x12!\n" +
	"\x1cPBMT_NTY_UNIXSOCK_UNREGISTER\x10\xd3\x01\x12#\n" +
	"\x1ePBMT_NTY_UNIXSOCK_DYNAMIC_LOAD\x10\xd5\x01\x12\"\n" +
	"\x1dPBMT_REQ_UNIXSOCK_CHG_PIPEIDX\x10\xd6\x01\x12\"\n" +
	"\x1dPBMT_RES_UNIXSOCK_CHG_PIPEIDX\x10\xd7\x01\x12\x1a\n" +
	"\x15PBMT_NTY_NET_HEATBEAT\x10\xad\x02\x12\x1a\n" +
	"\x15PBMT_REQ_NET_REGISTER\x10\xae\x02\x12\x1a\n" +
	"\x15PBMT_RSP_NET_REGISTER\x10\xaf\x02\x12\x1d\n" +
	"\x18PBMT_REQ_ROUTER_REGISTER\x10\xd9\x04\x12\x1d\n" +
	"\x18PBMT_RES_ROUTER_REGISTER\x10\xda\x04\x12\x1f\n" +
	"\x1aPBMT_REQ_ROUTER_UNREGISTER\x10\xdb\x04\x12\x1f\n" +
	"\x1aPBMT_RES_ROUTER_UNREGISTER\x10\xdc\x04\x12\x1b\n" +
	"\x16PBMT_REQ_START_MIGRATE\x10\xa1\x06\x12\x1b\n" +
	"\x16PBMT_RES_START_MIGRATE\x10\xa2\x06\x12$\n" +
	"\x1fPBMT_NTY_SIDECAR_MIGRATE_FINISH\x10\xa3\x06\x12\x1d\n" +
	"\x18PBMT_NTY_BACKENDSVR_STOP\x10\xa4\x06\x12#\n" +
	"\x1ePBMT_NTY_NEWSVR_MIGRATE_FINISH\x10\xa5\x06\x12\x0e\n" +
	"\bPBMT_MAX\x10\xe0\xd4\x03*A\n" +
	"\tESvrState\x12\r\n" +
	"\tST_HEALTH\x10\x00\x12\x14\n" +
	"\x10ST_GRACEFUL_EXIT\x10\x01\x12\x0f\n" +
	"\vST_FASTEXIT\x10\x02B)Z'github.com/linchenxuan/strix/network/pbb\x06proto3"

var (
	file_strix_mesh_proto_rawDescOnce sync.Once
	file_strix_mesh_proto_rawDescData []byte
)

func file_strix_mesh_proto_rawDescGZIP() []byte {
	file_strix_mesh_proto_rawDescOnce.Do(func() {
		file_strix_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strix_mesh_proto_rawDesc), len(file_strix_mesh_proto_rawDesc)))
	})
	return file_strix_mesh_proto_rawDescData
}

var file_strix_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_strix_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_strix_mesh_proto_goTypes = []any{
	(EPBMsgType)(0),                   // 0: mesh.EPBMsgType
	(ESvrState)(0),                    // 1: mesh.ESvrState
	(*NamingRegiserOption)(nil),       // 2: mesh.NamingRegiserOption
	(*ServiceQueryInfo)(nil),          // 3: mesh.ServiceQueryInfo
	(*MsgRspResult)(nil),              // 4: mesh.MsgRspResult
	(*MsgNtyUnixSockHeartBeat)(nil),   // 5: mesh.MsgNtyUnixSockHeartBeat
	(*MsgReqUnixSockRegister)(nil),    // 6: mesh.MsgReqUnixSockRegister
	(*MsgResUnixSockRegister)(nil),    // 7: mesh.MsgResUnixSockRegister
	(*MsgReqUnixSockChgPipeIdx)(nil),  // 8: mesh.MsgReqUnixSockChgPipeIdx
	(*MsgResUnixSockChgPipeIdx)(nil),  // 9: mesh.MsgResUnixSockChgPipeIdx
	(*MsgNtyUnixSockUnRegister)(nil),  // 10: mesh.MsgNtyUnixSockUnRegister
	(*MsgNtyUnixSockDynamicLoad)(nil), // 11: mesh.MsgNtyUnixSockDynamicLoad
	(*MsgNtyNetHeatBeat)(nil),         // 12: mesh.MsgNtyNetHeatBeat
	(*MsgReqNetRegister)(nil),         // 13: mesh.MsgReqNetRegister
	(*MsgResNetRegister)(nil),         // 14: mesh.MsgResNetRegister
}
var file_strix_mesh_proto_depIdxs = []int32{
	1, // 0: mesh.MsgNtyUnixSockHeartBeat.state:type_name -> mesh.ESvrState
	3, // 1: mesh.MsgReqUnixSockRegister.svc_info:type_name -> mesh.ServiceQueryInfo
	2, // 2: mesh.MsgReqUnixSockRegister.register_option:type_name -> mesh.NamingRegiserOption
	4, // 3: mesh.MsgResUnixSockRegister.result:type_name -> mesh.MsgRspResult
	3, // 4: mesh.MsgReqNetRegister.src_svc_info:type_name -> mesh.ServiceQueryInfo
	3, // 5: mesh.MsgReqNetRegister.dst_svc_info:type_name -> mesh.ServiceQueryInfo
	4, // 6: mesh.MsgResNetRegister.result:type_name -> mesh.MsgRspResult
	3, // 7: mesh.MsgResNetRegister.src_svc_info:type_name -> mesh.ServiceQueryInfo
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_strix_mesh_proto_init() }
func file_strix_mesh_proto_init() {
	if File_strix_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strix_mesh_proto_rawDesc), len(file_strix_mesh_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_strix_mesh_proto_goTypes,
		DependencyIndexes: file_strix_mesh_proto_depIdxs,
		EnumInfos:         file_strix_mesh_proto_enumTypes,
		MessageInfos:      file_strix_mesh_proto_msgTypes,
	}.Build()
	File_strix_mesh_proto = out.File
	file_strix_mesh_proto_goTypes = nil
	file_strix_mesh_proto_depIdxs = nil
}
